apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpanodejs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: psnodedeployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Pods
    pods:
      metricName: ian_node_requests
      targetAverageValue: 10000m
