apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-servicemonitor
  labels:
    release: ps 
spec:
  selector:
    matchLabels:
      app: psnode
  endpoints:
  - port: node
